version: 2
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Build
          command: ./script/build.sh latest
  deploy:
    steps:
      - run:
        name: Deploy
        command: curl -X POST -d '{"from":"circleci"}' "$DOCKER_REBUILD_URL"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master